In [1]:
import numpy as np
import torch
import torch.nn as nn
import matplotlib.pyplot as plt
%matplotlib inline

## 视觉层

In [2]:
##>1. 像素混淆 pixelshuffle
##把一个形状为[∗,(r^2)*C,H,W]的张量，重排为[∗,C,r*H,r*W]
input=torch.arange(144).reshape(1,9,4,4)
ps=nn.PixelShuffle(3)##r=3
out=ps(input)
out.shape

torch.Size([1, 1, 12, 12])

In [ ]:
##>2. upsample上采样

上采样，也称为图像插值，一般用来放大图片尺寸。
这里的采样模式（mode）如下：
- nearest neighbor，即最邻近：复制邻近值进行放大，适用3d,4d tensor
- linear，bilinear，即线性采样和双线性采样：适用于3d，4d tensor
- trilinear，三线性采样：适用于5d tensor

__注意:nn.Upsample类已经废置，适用nn.functional.interpolate进行代替__

In [3]:
##>2.1 Upsample
input=torch.arange(1,5).reshape(1,1,2,2).float()
input

tensor([[[[1., 2.],
          [3., 4.]]]])

In [4]:
m=nn.Upsample(scale_factor=2,mode='nearest')
m(input)

D:\Anaconda3-4.4.0\lib\site-packages\torch\nn\modules\upsampling.py:122: UserWarning: nn.Upsampling is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.Upsampling is deprecated. Use nn.functional.interpolate instead.")


tensor([[[[1., 1., 2., 2.],
          [1., 1., 2., 2.],
          [3., 3., 4., 4.],
          [3., 3., 4., 4.]]]])

In [7]:
##使用functional.interpolate进行代替
import torch.nn.functional as F
F.interpolate(input,scale_factor=2,mode='nearest')

tensor([[[[1., 1., 2., 2.],
          [1., 1., 2., 2.],
          [3., 3., 4., 4.],
          [3., 3., 4., 4.]]]])

In [9]:
F.interpolate(input,scale_factor=2,mode='bilinear',align_corners=False)

tensor([[[[1.0000, 1.2500, 1.7500, 2.0000],
          [1.5000, 1.7500, 2.2500, 2.5000],
          [2.5000, 2.7500, 3.2500, 3.5000],
          [3.0000, 3.2500, 3.7500, 4.0000]]]])

In [10]:
F.interpolate(input,scale_factor=2,mode='bilinear',align_corners=True)

tensor([[[[1.0000, 1.3333, 1.6667, 2.0000],
          [1.6667, 2.0000, 2.3333, 2.6667],
          [2.3333, 2.6667, 3.0000, 3.3333],
          [3.0000, 3.3333, 3.6667, 4.0000]]]])

In [11]:
input_3=torch.zeros(3,3).reshape(1,1,3,3).float()
input_3[:,:,:2,:2].copy_(input)
input_3

tensor([[[[1., 2., 0.],
          [3., 4., 0.],
          [0., 0., 0.]]]])

In [12]:
F.interpolate(input_3,scale_factor=2,mode='bilinear',align_corners=False)

tensor([[[[1.0000, 1.2500, 1.7500, 1.5000, 0.5000, 0.0000],
          [1.5000, 1.7500, 2.2500, 1.8750, 0.6250, 0.0000],
          [2.5000, 2.7500, 3.2500, 2.6250, 0.8750, 0.0000],
          [2.2500, 2.4375, 2.8125, 2.2500, 0.7500, 0.0000],
          [0.7500, 0.8125, 0.9375, 0.7500, 0.2500, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000]]]])

In [13]:
F.interpolate(input_3,scale_factor=2,mode='bilinear',align_corners=True)

tensor([[[[1.0000, 1.4000, 1.8000, 1.6000, 0.8000, 0.0000],
          [1.8000, 2.2000, 2.6000, 2.2400, 1.1200, 0.0000],
          [2.6000, 3.0000, 3.4000, 2.8800, 1.4400, 0.0000],
          [2.4000, 2.7200, 3.0400, 2.5600, 1.2800, 0.0000],
          [1.2000, 1.3600, 1.5200, 1.2800, 0.6400, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000]]]])

In [ ]:
##>2.2 其他的 UpsamplingNearest2d 和 UpsamplingBilinear2d，都可以用functional.interpolate代替