In [1]:
import numpy as np
import torch
import torch.nn as nn

#  模型序列化与反序列化

有两种方式进行模型的序列化：

## 方式一（推荐）：只序列化模型的参数

In [2]:
def init(m):
    if type(m) == nn.Linear:
        m.bias.data.fill_(1.0)
        m.weight.data.fill_(2.0)

In [3]:
model=nn.Linear(2,3)
model.apply(init)

Linear(in_features=2, out_features=3, bias=True)

In [4]:
for n,i in model.named_parameters():
    print(n,'-->',i)

weight --> Parameter containing:
tensor([[2., 2.],
        [2., 2.],
        [2., 2.]], requires_grad=True)
bias --> Parameter containing:
tensor([1., 1., 1.], requires_grad=True)


In [12]:
##序列化
torch.save(model.state_dict(),'./model/linear_mod.pt')

In [13]:
##反序列化
mod2=nn.Linear(2,3)
mod2.load_state_dict(torch.load('./model/linear_mod.pt'))


In [14]:
for n,i in model.named_parameters():
    print(n,'-->',i)

weight --> Parameter containing:
tensor([[2., 2.],
        [2., 2.],
        [2., 2.]], requires_grad=True)
bias --> Parameter containing:
tensor([1., 1., 1.], requires_grad=True)


## 方式二：序列化全部模型

In [15]:
torch.save(model,'./model/linear_mod_all.pt')

In [16]:
mod3=torch.load('./model/linear_mod_all.pt')

In [17]:
for n,i in model.named_parameters():
    print(n,'-->',i)

weight --> Parameter containing:
tensor([[2., 2.],
        [2., 2.],
        [2., 2.]], requires_grad=True)
bias --> Parameter containing:
tensor([1., 1., 1.], requires_grad=True)


>这种方式下序列化数据被绑定到指定的类，并且使用了特定的目录结构.

>因此当在其他项目中使用时，可能有很多原因造成模型毁坏.