In [1]:
import numpy as np
import torch
import torch.nn as nn
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
##>1. BatchNorm1d
x=torch.arange(1,13,dtype=torch.float).reshape(3,4)
x

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [3]:
m=nn.BatchNorm1d(4)##参数或者是通道数，或者是长度
m(x)

tensor([[-0.3910, -0.0201, -0.2852, -0.3220],
        [ 0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.3910,  0.0201,  0.2852,  0.3220]],
       grad_fn=<ThnnBatchNormBackward>)

In [4]:
mean=torch.mean(x,dim=0)
mean

tensor([5., 6., 7., 8.])

In [5]:
std=torch.std(x,dim=0)
std

tensor([4., 4., 4., 4.])

In [6]:
(x-mean)/std

tensor([[-1., -1., -1., -1.],
        [ 0.,  0.,  0.,  0.],
        [ 1.,  1.,  1.,  1.]])

### 对比out3与out6，同样是标准化，结果不太一样
参考:https://pytorch.org/docs/stable/nn.html#torch.nn.BatchNorm1d

In [11]:
##>2. BatchNorm2d
x=torch.arange(32,dtype=torch.float).reshape(1,2,4,4)
m=nn.BatchNorm2d(2)##参数是通道数
x

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]],

         [[16., 17., 18., 19.],
          [20., 21., 22., 23.],
          [24., 25., 26., 27.],
          [28., 29., 30., 31.]]]])

In [12]:
m(x)

tensor([[[[-0.9850, -0.8537, -0.7224, -0.5910],
          [-0.4597, -0.3283, -0.1970, -0.0657],
          [ 0.0657,  0.1970,  0.3283,  0.4597],
          [ 0.5910,  0.7224,  0.8537,  0.9850]],

         [[-1.5173, -1.3150, -1.1127, -0.9104],
          [-0.7081, -0.5058, -0.3035, -0.1012],
          [ 0.1012,  0.3035,  0.5058,  0.7081],
          [ 0.9104,  1.1127,  1.3150,  1.5173]]]],
       grad_fn=<ThnnBatchNormBackward>)

In [15]:
##>3. GroupNormal
##把通道分组然后进行标准化
x=torch.arange(24,dtype=torch.float).reshape(1,6,2,2)
m=nn.GroupNorm(3,6)##6个通道分为3组
x

tensor([[[[ 0.,  1.],
          [ 2.,  3.]],

         [[ 4.,  5.],
          [ 6.,  7.]],

         [[ 8.,  9.],
          [10., 11.]],

         [[12., 13.],
          [14., 15.]],

         [[16., 17.],
          [18., 19.]],

         [[20., 21.],
          [22., 23.]]]])

In [16]:
m(x)

tensor([[[[-1.5275, -1.0911],
          [-0.6547, -0.2182]],

         [[ 0.2182,  0.6547],
          [ 1.0911,  1.5275]],

         [[-1.5275, -1.0911],
          [-0.6547, -0.2182]],

         [[ 0.2182,  0.6547],
          [ 1.0911,  1.5275]],

         [[-1.5275, -1.0911],
          [-0.6547, -0.2182]],

         [[ 0.2182,  0.6547],
          [ 1.0911,  1.5275]]]], grad_fn=<AddcmulBackward>)

In [19]:
##>4. 一维实例标准化 InstanceNorm1d
x=torch.arange(1,13,dtype=torch.float).reshape(2,3,2)
m=nn.InstanceNorm1d(3)##参数是通道数
m(x)

tensor([[[-1.0000,  1.0000],
         [-1.0000,  1.0000],
         [-1.0000,  1.0000]],

        [[-1.0000,  1.0000],
         [-1.0000,  1.0000],
         [-1.0000,  1.0000]]])

In [20]:
##>5. 二维实例标准化 InstanceNorm2d
x=torch.arange(32,dtype=torch.float).reshape(1,2,4,4)
m=nn.InstanceNorm2d(4)
m(x)

tensor([[[[-1.6270, -1.4100, -1.1931, -0.9762],
          [-0.7593, -0.5423, -0.3254, -0.1085],
          [ 0.1085,  0.3254,  0.5423,  0.7593],
          [ 0.9762,  1.1931,  1.4100,  1.6270]],

         [[-1.6270, -1.4100, -1.1931, -0.9762],
          [-0.7593, -0.5423, -0.3254, -0.1085],
          [ 0.1085,  0.3254,  0.5423,  0.7593],
          [ 0.9762,  1.1931,  1.4100,  1.6270]]]])

In [21]:
##>6. 层标准化LayerNormalization

In [ ]:
##>7. LocalResponseNorm