In [1]:
import numpy as np
import torch
import torch.nn as nn
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
#一 线性层
##>1.1 Linear
x=torch.randn(128,20)
m=nn.Linear(20,10)##input_features,output_features,bias=True
y=m(x)
y.shape

torch.Size([128, 10])

In [10]:
##注意它有两个类型为parameter的参数：一个是weight，一个是bias
print(type(m.weight),'\n',type(m.bias))

<class 'torch.nn.parameter.Parameter'> 
 <class 'torch.nn.parameter.Parameter'>


In [5]:
m.weight.shape

torch.Size([10, 20])

In [8]:
m.bias.data

tensor([-0.1344,  0.1852,  0.0285, -0.1768,  0.1633, -0.0574, -0.1533, -0.2139,
         0.2019, -0.1428])

In [11]:
##初始化
m2=nn.Linear(5,3)
def init(m):
    m.bias.data.fill_(1.1)
    m.weight.data.fill_(0.5)
m2.apply(init)
m2.weight.data

tensor([[0.5000, 0.5000, 0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000, 0.5000, 0.5000]])

In [12]:
for n,i in m2.named_parameters():
    print(n,'-->',i)

weight --> Parameter containing:
tensor([[0.5000, 0.5000, 0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000, 0.5000, 0.5000]], requires_grad=True)
bias --> Parameter containing:
tensor([1.1000, 1.1000, 1.1000], requires_grad=True)


In [16]:
##>1.2 Bilinear
m=nn.Bilinear(2,3,4)
input1=torch.arange(8,dtype=torch.float).reshape(4,2)
input2=torch.arange(12,dtype=torch.float).reshape(4,3)
def init2(m):
    m.weight.data.fill_(1.0)
    m.bias.data.fill_(2.0)

m.apply(init2)
m.weight.data.shape

torch.Size([4, 2, 3])

In [20]:
out=m(input1,input2)
out.shape

torch.Size([4, 4])

In [ ]:
#二 dropout层
##>2.1 Dropout

在训练过程中，随机把输入张量的一些元素以p概率置0，可以：
- 有效正则化
- 防止神经元的共适应

p默认为0.5

In [32]:
m=nn.Dropout()
x=torch.randn(4,3)
y=torch.arange(12,dtype=torch.float).reshape(4,3)
y

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])

In [33]:
m(y)

tensor([[ 0.,  2.,  4.],
        [ 0.,  8., 10.],
        [ 0., 14.,  0.],
        [ 0., 20.,  0.]])

__除了置0以外，非0输出会以$\frac{1}{1-p}$的比例进行缩放__

In [42]:
##>2.2 Dropout2d
m=nn.Dropout2d()
x=torch.arange(32,dtype=torch.float).reshape(1,2,4,4)
m(x)

tensor([[[[ 0.,  2.,  4.,  6.],
          [ 8., 10., 12., 14.],
          [16., 18., 20., 22.],
          [24., 26., 28., 30.]],

         [[ 0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.]]]])

dropout2d的置0与缩放，针对的是整个channel

In [43]:
##>2.3 alphadropout

In [44]:
#>三 稀疏层
##>3.1 Embedding

In [45]:
##>3.2 EmbeddingGag