In [1]:
import numpy as np
import torch
import torch.nn as nn
import matplotlib.pyplot as plt
%matplotlib inline

- 池化层没有输入、输出通道的参数。就是说，池化前后通道不会发生变化。
- 通常池化就是缩小图片的尺寸。

In [6]:
#>一 最大池化
##>1.1 一维池化
m=nn.MaxPool1d(3,stride=2,return_indices=True)##核为3
input=torch.randn(1,1,50)
out=m(input)
out[0]##由于return_indices为True，因此返回一个tuple：一个元素是池化后的值，第二个元素是最大池化的坐标

tensor([[[ 1.3067,  1.3067,  0.6895,  0.8300,  0.6982,  0.5993,  0.5993,
          -0.6316,  1.0830,  1.0830,  0.6166, -0.8010,  0.7991,  2.2418,
           2.2418,  0.7325,  0.7325,  0.3906,  0.3753,  0.4103,  1.2238,
           1.2238,  0.6592,  0.9682]]])

In [7]:
out[1]

tensor([[[ 2,  2,  6,  7,  9, 12, 12, 16, 18, 18, 21, 22, 26, 28, 28, 32, 32,
          35, 37, 39, 42, 42, 45, 47]]])

In [8]:
input

tensor([[[ 0.5033,  0.0907,  1.3067, -0.8518, -0.4917, -0.0422,  0.6895,
           0.8300,  0.3823,  0.6982, -0.1970, -0.3829,  0.5993, -0.8318,
          -1.6318, -0.7554, -0.6316, -1.6443,  1.0830, -0.9699,  0.3147,
           0.6166, -0.8010, -1.5187, -0.8879,  0.2839,  0.7991, -0.3653,
           2.2418,  1.1889, -0.2536, -0.2034,  0.7325, -0.9748,  0.1103,
           0.3906, -0.0236,  0.3753, -0.4997,  0.4103, -0.6522,  0.8339,
           1.2238, -1.0287,  0.0002,  0.6592,  0.0311,  0.9682,  0.7490,
          -2.0412]]])

In [9]:
##>1.2 二维池化
m=nn.MaxPool2d((3,2),stride=(2,1))
input=torch.randn(20,16,50,32)
out=m(input)
out.shape

torch.Size([20, 16, 24, 31])

In [10]:
##>1.3 三维池化
m=nn.MaxPool3d((3,2,2),stride=(2,1,2))
input=torch.randn(20,16,50,44,31)
out=m(input)
out.shape

torch.Size([20, 16, 24, 43, 15])

- 逆池化相当于把缩小的图片尺寸恢复为原来的尺寸
- 逆最大池化只能恢复最大的元素，其他的元素均为0

In [36]:
#>2. 逆最大池化
##>2.1 一维逆最大池化
pool=nn.MaxPool1d(2,stride=2,return_indices=True)
unpool=nn.MaxUnpool1d(2,stride=2)
input=torch.arange(1,9,dtype=torch.float).reshape(-1,8).unsqueeze(1)
input

tensor([[[1., 2., 3., 4., 5., 6., 7., 8.]]])

In [38]:
out,indices=pool(input)
indices

tensor([[[1, 3, 5, 7]]])

In [39]:
unpool(out,indices)

tensor([[[0., 2., 0., 4., 0., 6., 0., 8.]]])

In [41]:
input=torch.arange(1,10,dtype=torch.float).reshape(-1,9).unsqueeze(1)##注意input的size是9
out,indices=pool(input)

In [42]:
unpool(out,indices)##input的size是9，这里没有设置output_size，因此unpool后，大小与原先的并不一致

tensor([[[0., 2., 0., 4., 0., 6., 0., 8.]]])

In [43]:
unpool(out,indices,output_size=input.size())##这里设置了output_size与input.size一样大，因此unpool后，尺寸与原先的一样

tensor([[[0., 2., 0., 4., 0., 6., 0., 8., 0.]]])

In [46]:
##>2.2 二维逆最大池化
pool=nn.MaxPool2d(2,stride=2,return_indices=True)
unpool=nn.MaxUnpool2d(2,stride=2)
input=torch.arange(1,17,dtype=torch.float).reshape(1,1,4,4)
input

tensor([[[[ 1.,  2.,  3.,  4.],
          [ 5.,  6.,  7.,  8.],
          [ 9., 10., 11., 12.],
          [13., 14., 15., 16.]]]])

In [49]:
out,indices=pool(input)
out

tensor([[[[ 6.,  8.],
          [14., 16.]]]])

In [50]:
unpool(out,indices)##恢复为原先的形状，除最大元素外，其他元素为 0

tensor([[[[ 0.,  0.,  0.,  0.],
          [ 0.,  6.,  0.,  8.],
          [ 0.,  0.,  0.,  0.],
          [ 0., 14.,  0., 16.]]]])

In [51]:
#>3. 平均池化
##>3.1 二维平均池化
m=nn.AvgPool2d((3,2),stride=(2,1))
input=torch.randn(20,16,50,32)
out=m(input)
out.shape

torch.Size([20, 16, 24, 31])

In [54]:
#>4. LP范数池化
input=torch.arange(1,5,dtype=torch.float).reshape(1,1,4)
pool=nn.LPPool1d(2,2)##取2-范数，核为2，其他参数默认
out=pool(input)
out

tensor([[[2.2361, 5.0000]]])

In [ ]:
#>5. 自适应最大池化

- 自适应最大池化只需要指定输出的目标尺寸即可，其他参数自动计算

In [55]:
##>5.1 一维自适应最大池化
input=torch.randn(1,64,8)
m=nn.AdaptiveMaxPool1d(5)#目标尺寸为5
out=m(input)
out.shape

torch.Size([1, 64, 5])

In [56]:
##>5.2 二维自适应最大池化
input=torch.randn(1,34,8,9)
m=nn.AdaptiveMaxPool2d((5,7))#目标尺寸：H=5,W=7
out=m(input)
out.shape

torch.Size([1, 34, 5, 7])

In [57]:
m=nn.AdaptiveMaxPool2d(7)##目标输出为方阵
out=m(input)
out.shape

torch.Size([1, 34, 7, 7])

In [59]:
m=nn.AdaptiveAvgPool2d((None,7))##可以只指定一个维度的尺寸
out=m(input)
out.shape

torch.Size([1, 34, 8, 7])

In [60]:
#>6. 自适应平均池化
##>6.1 二维自适应平均池化
m=nn.AdaptiveAvgPool2d((5,7))
out=m(input)
out.shape

torch.Size([1, 34, 5, 7])

In [63]:
#############test###########
m=nn.Conv1d(4,4,2,stride=2)
input=torch.arange(16,dtype=torch.float).reshape(1,4,4)
input

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.]]])

In [65]:
out=m(input)
out.shape

torch.Size([1, 4, 2])

In [68]:
out

tensor([[[ -1.7420,  -2.7894],
         [ -8.2981, -10.9620],
         [  5.0127,   5.1771],
         [  2.8058,   2.2444]]], grad_fn=<SqueezeBackward1>)