### padding层就是给输入数据的边界做一定数量的扩充，以进行卷积和池化
有以下分类：
- 镜像 padding
- 复制 padding
- 0 padding
- 常数 padding

In [1]:
import numpy as np
import torch
import torch.nn as nn
import matplotlib.pyplot as plt
%matplotlib inline


In [10]:
#>一 镜像 padding
##>1.1 一维镜像padding
m1=nn.ReflectionPad1d(2)##left=right=2
m2=nn.ReflectionPad1d((2,1))##left=2,right=1
input=torch.arange(8,dtype=torch.float).reshape(1,2,4)
input

tensor([[[0., 1., 2., 3.],
         [4., 5., 6., 7.]]])

In [11]:
m1(input)

tensor([[[2., 1., 0., 1., 2., 3., 2., 1.],
         [6., 5., 4., 5., 6., 7., 6., 5.]]])

In [12]:
m2(input)

tensor([[[2., 1., 0., 1., 2., 3., 2.],
         [6., 5., 4., 5., 6., 7., 6.]]])

In [13]:
##>1.2 二维镜像padding
m1=nn.ReflectionPad2d(2)#left=right=top=bottom=2
m2=nn.ReflectionPad2d((1,1,2,0))#left=right=1,top=2,bottom=0
input=torch.arange(9,dtype=torch.float).reshape(1,1,3,3)
input

tensor([[[[0., 1., 2.],
          [3., 4., 5.],
          [6., 7., 8.]]]])

In [14]:
m1(input)

tensor([[[[8., 7., 6., 7., 8., 7., 6.],
          [5., 4., 3., 4., 5., 4., 3.],
          [2., 1., 0., 1., 2., 1., 0.],
          [5., 4., 3., 4., 5., 4., 3.],
          [8., 7., 6., 7., 8., 7., 6.],
          [5., 4., 3., 4., 5., 4., 3.],
          [2., 1., 0., 1., 2., 1., 0.]]]])

In [15]:
m2(input)

tensor([[[[7., 6., 7., 8., 7.],
          [4., 3., 4., 5., 4.],
          [1., 0., 1., 2., 1.],
          [4., 3., 4., 5., 4.],
          [7., 6., 7., 8., 7.]]]])

In [16]:
#>二 复制 padding
##>2.1 一维复制padding
m1=nn.ReplicationPad1d(2)
m2=nn.ReplicationPad1d((2,1))
input_1d=torch.arange(8,dtype=torch.float).reshape(1,2,4)
input_2d=torch.arange(9,dtype=torch.float).reshape(1,1,3,3)

In [17]:
m1(input_1d)

tensor([[[0., 0., 0., 1., 2., 3., 3., 3.],
         [4., 4., 4., 5., 6., 7., 7., 7.]]])

In [19]:
m2(input_1d)

tensor([[[0., 0., 0., 1., 2., 3., 3.],
         [4., 4., 4., 5., 6., 7., 7.]]])

In [20]:
##>2.2 二维复制padding
m1=nn.ReplicationPad2d(2)
m2=nn.ReflectionPad2d((1,1,2,0))
m1(input_2d)

tensor([[[[0., 0., 0., 1., 2., 2., 2.],
          [0., 0., 0., 1., 2., 2., 2.],
          [0., 0., 0., 1., 2., 2., 2.],
          [3., 3., 3., 4., 5., 5., 5.],
          [6., 6., 6., 7., 8., 8., 8.],
          [6., 6., 6., 7., 8., 8., 8.],
          [6., 6., 6., 7., 8., 8., 8.]]]])

In [21]:
m2(input_2d)

tensor([[[[7., 6., 7., 8., 7.],
          [4., 3., 4., 5., 4.],
          [1., 0., 1., 2., 1.],
          [4., 3., 4., 5., 4.],
          [7., 6., 7., 8., 7.]]]])

In [22]:
#>三 零padding
m1=nn.ZeroPad2d(2)
m2=nn.ZeroPad2d((1,1,2,0))
m1(input_2d)

tensor([[[[0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 1., 2., 0., 0.],
          [0., 0., 3., 4., 5., 0., 0.],
          [0., 0., 6., 7., 8., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0.]]]])

In [23]:
m2(input_2d)

tensor([[[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 1., 2., 0.],
          [0., 3., 4., 5., 0.],
          [0., 6., 7., 8., 0.]]]])

In [28]:
#>四 常数padding
##>4.1 一维常数padding
m1=nn.ConstantPad1d(2,1.1)
m2=nn.ConstantPad1d((2,1),1.2)
m1(input_1d)

tensor([[[1.1000, 1.1000, 0.0000, 1.0000, 2.0000, 3.0000, 1.1000, 1.1000],
         [1.1000, 1.1000, 4.0000, 5.0000, 6.0000, 7.0000, 1.1000, 1.1000]]])

In [29]:
m2(input_1d)

tensor([[[1.2000, 1.2000, 0.0000, 1.0000, 2.0000, 3.0000, 1.2000],
         [1.2000, 1.2000, 4.0000, 5.0000, 6.0000, 7.0000, 1.2000]]])

In [30]:
##>4.2 二维常数padding
m1=nn.ConstantPad2d(2,0.22)
m2=nn.ConstantPad2d((1,1,2,0),0.33)
m1(input_2d)

tensor([[[[0.2200, 0.2200, 0.2200, 0.2200, 0.2200, 0.2200, 0.2200],
          [0.2200, 0.2200, 0.2200, 0.2200, 0.2200, 0.2200, 0.2200],
          [0.2200, 0.2200, 0.0000, 1.0000, 2.0000, 0.2200, 0.2200],
          [0.2200, 0.2200, 3.0000, 4.0000, 5.0000, 0.2200, 0.2200],
          [0.2200, 0.2200, 6.0000, 7.0000, 8.0000, 0.2200, 0.2200],
          [0.2200, 0.2200, 0.2200, 0.2200, 0.2200, 0.2200, 0.2200],
          [0.2200, 0.2200, 0.2200, 0.2200, 0.2200, 0.2200, 0.2200]]]])

In [31]:
m2(input_2d)

tensor([[[[0.3300, 0.3300, 0.3300, 0.3300, 0.3300],
          [0.3300, 0.3300, 0.3300, 0.3300, 0.3300],
          [0.3300, 0.0000, 1.0000, 2.0000, 0.3300],
          [0.3300, 3.0000, 4.0000, 5.0000, 0.3300],
          [0.3300, 6.0000, 7.0000, 8.0000, 0.3300]]]])