In [1]:
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
import torch.utils.data as data

### 1. Dataset

抽象类，供继承. 其子类主要供DataLoader使用.
需要实现：
- \_\_getitem\_\_
- \_\_len\_\_

### 2. TensorDataset

Dataset子类.
- 所有的数据第一维（dim=0）尺寸必须相等
- 按索引取数据时，从第一维开始取，返回tuple

In [23]:
x=torch.randn(2,2)

In [34]:
y=torch.arange(10).reshape(2,-1)
d=data.TensorDataset(x,y)
print(x,'\n',y)

tensor([[-2.2755, -0.1234],
        [ 1.0340,  0.9306]]) 
 tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


In [28]:
print(len(d),'\n',d[0])

2 
 (tensor([-2.2755, -0.1234]), tensor([0, 1, 2, 3, 4]))


### 3.ConcatDataset

Dataset子类.

In [54]:
y2=torch.arange(10,14).reshape(1,-1)##ContcatDataset不要求各dataset第一维大小一致
d2=data.TensorDataset(y2)
cd=data.ConcatDataset([d,d2])

In [55]:
cd[0]

(tensor([-2.2755, -0.1234]), tensor([0, 1, 2, 3, 4]))

In [51]:
cd[1]

(tensor([1.0340, 0.9306]), tensor([5, 6, 7, 8, 9]))

In [56]:
cd[2]

(tensor([10, 11, 12, 13]),)

In [58]:
len(cd)

3

### 4.Subset

Dataset子类.

用于选取Dataset的子集

In [65]:
s=data.Subset(cd,[1,2])
s[0]

(tensor([1.0340, 0.9306]), tensor([5, 6, 7, 8, 9]))

In [66]:

s[1]

(tensor([10, 11, 12, 13]),)

### 5.DataLoader

组合Dataset、采样器、以及单线程或多线程的迭代器，实现对数据的弹性加载.

主要用在数据的加载与处理方面.

见：https://pytorch.org/tutorials/beginner/data_loading_tutorial.html

### 6. random_split 数据切分

按给定长度随机切分数据.

### 7. 采样器基类 Sampler
每个子类需要提供 __iter__ 和__len__ 方法.

### 8.各采样器子类

- RandomSampler:随机采样，无放回（without replacement）


- SequentialSampler：顺序采样，总是保持相同顺序


- SubsetRandomSampler：从给定的索引中随机采样，无放回


- WeightedRandomSampler：带权重的随机抽样，默认有放回


- BactchSampler：批采样


- DistributedSampler：分布式采样

In [75]:
## BatchSampler+SequentialSampler
list(torch.utils.data.BatchSampler(torch.utils.data.SequentialSampler(range(10)),batch_size=3,drop_last=False))

[[0, 1, 2], [3, 4, 5], [6, 7, 8], [9]]

In [76]:
list(torch.utils.data.BatchSampler(torch.utils.data.SequentialSampler(range(10)),batch_size=3,drop_last=True))

[[0, 1, 2], [3, 4, 5], [6, 7, 8]]